on:
  workflow_call:
    inputs:
      php_versions:
        description: PHP versions in JSON array format
        type: string
        default: '["8.3", "8.4"]'
      dependencies:
        description: Dependency versions (locked, lowest, highest) in JSON array format
        type: string
        default: '["locked", "lowest", "highest"]'
      phpstan:
        type: boolean
        default: true
      psalm:
        type: boolean
        default: false
    secrets:
      COMPOSER_AUTH:
        required: false
        
jobs:
  composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ fromJSON(inputs.php_versions)[0] }}
          tools: composer:v2
          coverage: none
      - run: composer validate
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH || '{}' }}
      - run: composer normalize --dry-run
      - run: composer analyse-deps

  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ fromJSON(inputs.php_versions)[0] }}
          tools: composer:v2, cs2pr
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH || '{}' }}
      - run: composer fixcs -- --dry-run --format=checkstyle | cs2pr

  phpstan:
    if: inputs.phpstan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ${{ fromJson(inputs.php_versions) }}
        dependencies: ${{ fromJson(inputs.dependencies) }}
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
          dependency-versions: ${{ matrix.dependencies }}
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH || '{}' }}
      - run: composer phpstan -- --error-format=github

  psalm:
    if: inputs.psalm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ${{ fromJson(inputs.php_versions) }}
        dependencies: ${{ fromJson(inputs.dependencies) }}
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
          dependency-versions: ${{ matrix.dependencies }}
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH || '{}' }}
      - run: composer psalm -- --stats --output-format=github ${{ (matrix.php == fromJson(inputs.php_versions)[0]) && (matrix.dependencies == fromJson(inputs.dependencies)[0]) && '--shepherd' || '' }}
        